// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGIc4VGNhBdj5VPzegWVnuMWusHMes17c',
    appId: '1:517361226956:web:05ded675fe0cf86655de69',
    messagingSenderId: '517361226956',
    projectId: 'contact-mangers',
    authDomain: 'contact-mangers.firebaseapp.com',
    storageBucket: 'contact-mangers.appspot.com',
    measurementId: 'G-B7ZFW6RBL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3U6g9xosDnzqepmmeZ9KBo65rc3n91U',
    appId: '1:517361226956:android:99d11db5215d399655de69',
    messagingSenderId: '517361226956',
    projectId: 'contact-mangers',
    storageBucket: 'contact-mangers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiTTuHTq0pY_H70iOct_elIi4eq5-UPQ',
    appId: '1:517361226956:ios:f637bbc863283a8655de69',
    messagingSenderId: '517361226956',
    projectId: 'contact-mangers',
    storageBucket: 'contact-mangers.appspot.com',
    iosClientId: '517361226956-i8b8no58e3jbu1j901ls5oi63ajmnuk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactManagers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqiTTuHTq0pY_H70iOct_elIi4eq5-UPQ',
    appId: '1:517361226956:ios:f637bbc863283a8655de69',
    messagingSenderId: '517361226956',
    projectId: 'contact-mangers',
    storageBucket: 'contact-mangers.appspot.com',
    iosClientId: '517361226956-i8b8no58e3jbu1j901ls5oi63ajmnuk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactManagers',
  );
}
